# Generated by Django 6.0.5 on 2026-05-08 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiket', '0005_alter_transaction_transaction_type_payoutaccount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='trans_id',
            new_name='reference',
        ),
    ]
