# Generated by Django 6.0.5 on 2026-05-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiket', '0007_transaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
