# Generated by Django 6.0.5 on 2026-05-09 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiket', '0008_event_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
