# Generated by Django 6.0.5 on 2026-05-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiket', '0010_transaction_amount_paid_transaction_gross_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bx_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
