# Generated by Django 6.0.5 on 2026-05-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiket', '0011_transaction_bx_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
